const { app, BrowserWindow, dialog, ipcMain, shell } = require('electron');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const crypto = require('node:crypto');

const root = path.join(__dirname, '..');
const backend = path.join(root, 'backend');
const jobs = new Map();
let window;

function pythonBin(requested) { return requested && String(requested).trim() || 'python3'; }
function send(payload) { if (window && !window.isDestroyed()) window.webContents.send('job-event', payload); }
function createWindow() {
  window = new BrowserWindow({
    width: 1512, height: 960, minWidth: 1120, minHeight: 700,
    backgroundColor: '#f5f5f1', titleBarStyle: 'hiddenInset',
    webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: true }
  });
  if (!app.isPackaged && process.env.VITE_DEV_SERVER_URL) window.loadURL(process.env.VITE_DEV_SERVER_URL);
  else if (!app.isPackaged && process.env.npm_lifecycle_event === 'dev') window.loadURL('http://127.0.0.1:5173');
  else window.loadFile(path.join(root, 'dist', 'index.html'));
}

app.whenReady().then(() => {
  createWindow();
  app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });
});
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
app.on('before-quit', () => { for (const child of jobs.values()) child.kill('SIGTERM'); });

ipcMain.handle('system', async () => ({
  platform: process.platform,
  defaultOutput: path.join(app.getPath('documents'), 'BananaAll', 'runs'),
  python: 'python3'
}));
ipcMain.handle('pick-path', async (_e, kind) => {
  const options = kind === 'directory'
    ? { properties: ['openDirectory', 'createDirectory'] }
    : { properties: ['openFile'], filters: [{ name: 'Datasets or Python', extensions: ['json', 'jsonl', 'csv', 'parquet', 'py', 'txt'] }] };
  const result = await dialog.showOpenDialog(window, options);
  return result.canceled ? null : result.filePaths[0];
});
ipcMain.handle('open-path', async (_e, target) => {
  if (!target || typeof target !== 'string') return 'No path supplied';
  return shell.openPath(path.resolve(target));
});
ipcMain.handle('training-code', async (_e, configPath, modelingPath) => {
  const source = fs.readFileSync(path.join(backend, 'train.py'), 'utf8');
  const configuration = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  if (!fs.statSync(modelingPath).isFile()) throw new Error('Modeling Python file not found');
  const summary = JSON.stringify(configuration, null, 2).split('\n').map(line => `# ${line}`).join('\n');
  const header = `# Generated by BananaAll for this custom architecture.\n# Config: ${configPath}\n# Modeling: ${modelingPath}\n# Review the custom loading path in make_model() before running.\n# Configuration supplied for this run:\n${summary}\n\n`;
  return header + source;
});

function runCollect(args, python, timeoutMs = 90000) {
  return new Promise((resolve, reject) => {
    const child = spawn(pythonBin(python), args, { cwd: backend, env: { ...process.env, PYTHONUNBUFFERED: '1' } });
    let stdout = '', stderr = '';
    const timer = setTimeout(() => { child.kill('SIGTERM'); reject(new Error('Dataset preview timed out. Try a smaller or local dataset.')); }, timeoutMs);
    child.stdout.on('data', d => { stdout += d; });
    child.stderr.on('data', d => { stderr += d; });
    child.on('error', err => { clearTimeout(timer); reject(err); });
    child.on('close', code => {
      clearTimeout(timer);
      if (code !== 0) return reject(new Error(stderr.trim() || stdout.trim() || `Python exited with ${code}`));
      try { resolve(JSON.parse(stdout.trim())); } catch { reject(new Error(stderr.trim() || 'Could not parse dataset preview')); }
    });
  });
}
ipcMain.handle('inspect-dataset', async (_e, source, python) => {
  return runCollect([path.join(backend, 'inspect_dataset.py'), JSON.stringify(source)], python);
});
ipcMain.handle('auth-status', async (_e, python) => runCollect([path.join(backend, 'auth_status.py')], python, 20000));

ipcMain.handle('start-job', async (_e, kind, config, code) => {
  if (!['train', 'evaluate', 'infer'].includes(kind)) throw new Error('Unknown job type');
  const id = crypto.randomUUID();
  const output = path.resolve(config.outputDir || path.join(app.getPath('documents'), 'BananaAll', 'runs'), kind === 'train' ? (config.runName || `run-${id.slice(0, 8)}`) : `job-${id.slice(0, 8)}`);
  fs.mkdirSync(output, { recursive: true });
  const configFile = path.join(output, 'bananaall-config.json');
  fs.writeFileSync(configFile, JSON.stringify({ ...config, outputPath: output }, null, 2));
  let script = path.join(backend, `${kind}.py`);
  if (kind === 'train' && typeof code === 'string' && code.trim()) {
    script = path.join(output, 'training_code.py');
    fs.writeFileSync(script, code);
  }
  const child = spawn(pythonBin(config.python), [script, configFile], { cwd: backend, env: { ...process.env, PYTHONUNBUFFERED: '1', PYTHONPATH: `${backend}${path.delimiter}${process.env.PYTHONPATH || ''}` } });
  jobs.set(id, child);
  let buffer = '';
  child.stdout.on('data', chunk => {
    buffer += chunk.toString();
    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop();
    for (const line of lines) {
      if (!line.trim()) continue;
      try { send({ id, ...JSON.parse(line) }); }
      catch { send({ id, type: 'log', message: line }); }
    }
  });
  child.stderr.on('data', chunk => send({ id, type: 'log', message: chunk.toString() }));
  child.on('error', err => { jobs.delete(id); send({ id, type: 'error', message: err.message }); });
  child.on('close', code => {
    jobs.delete(id);
    if (buffer.trim()) send({ id, type: 'log', message: buffer });
    send({ id, type: 'exit', code, outputPath: output });
  });
  return { id, outputPath: output };
});
ipcMain.handle('stop-job', async (_e, id) => {
  const child = jobs.get(id);
  if (!child) return false;
  child.kill('SIGTERM');
  return true;
});
