const { app, BrowserWindow, dialog, ipcMain, shell } = require('electron');
const { spawn, spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const crypto = require('node:crypto');
const { buildNotebook, safeName, validateNotebookConfig } = require('./notebook.cjs');
const openrouter = require('./openrouter.cjs');

const root = path.join(__dirname, '..');
const backend = path.join(root, 'backend');
const jobs = new Map();
const stoppingJobs = new Set();
const completedJobs = new Set();
let window;

function pythonBin(requested) { return requested && String(requested).trim() || 'python3'; }
function detectWindowsPython() {
  const localPython = path.join(root, '.venv', 'Scripts', 'python.exe');
  const commands = [localPython, 'python', 'python3', 'py'];
  for (const command of commands) {
    if (command === localPython && !fs.existsSync(localPython)) continue;
    const result = spawnSync(command, ['-c', 'import sys; print(sys.executable)'], {
      encoding: 'utf8', timeout: 5000, windowsHide: true
    });
    const executable = result.status === 0 && result.stdout && result.stdout.trim();
    if (executable) return executable;
  }
  return 'python';
}
function send(payload) { if (window && !window.isDestroyed()) window.webContents.send('job-event', payload); }
function createWindow() {
  window = new BrowserWindow({
    width: 1512, height: 960, minWidth: 1120, minHeight: 700,
    backgroundColor: '#f5f5f1', titleBarStyle: 'hiddenInset',
    webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: true }
  });
  if (!app.isPackaged && process.env.VITE_DEV_SERVER_URL) window.loadURL(process.env.VITE_DEV_SERVER_URL);
  else if (!app.isPackaged && process.env.npm_lifecycle_event === 'dev') window.loadURL('http://127.0.0.1:5173');
  else window.loadFile(path.join(root, 'dist', 'index.html'));
}

app.whenReady().then(() => {
  createWindow();
  app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });
});
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
app.on('before-quit', () => { for (const child of jobs.values()) child.kill('SIGTERM'); });

ipcMain.handle('system', async () => ({
  platform: process.platform,
  defaultOutput: path.join(app.getPath('documents'), 'BananaAll', 'runs'),
  python: process.platform === 'win32' ? detectWindowsPython() : 'python3'
}));
ipcMain.handle('pick-path', async (_e, kind) => {
  const options = kind === 'directory'
    ? { properties: ['openDirectory', 'createDirectory'] }
    : { properties: ['openFile'], filters: [{ name: 'Datasets or Python', extensions: ['json', 'jsonl', 'csv', 'parquet', 'py', 'txt'] }] };
  const result = await dialog.showOpenDialog(window, options);
  return result.canceled ? null : result.filePaths[0];
});
ipcMain.handle('open-path', async (_e, target) => {
  if (!target || typeof target !== 'string') return 'No path supplied';
  return shell.openPath(path.resolve(target));
});
ipcMain.handle('review-settings', async () => openrouter.status());
ipcMain.handle('review-key-save', async (_e, key) => openrouter.saveKey(key));
ipcMain.handle('review-key-clear', async () => openrouter.clearKey());
ipcMain.handle('review-setup-skip', async () => openrouter.finishSetup());
ipcMain.handle('ai-review', async (_e, request) => openrouter.review(request));
ipcMain.handle('training-code', async (_e, configPath, configurationPath, modelingPath) => {
  const source = fs.readFileSync(path.join(backend, 'train.py'), 'utf8');
  const configuration = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  if (!fs.statSync(configurationPath).isFile() || path.extname(configurationPath) !== '.py') throw new Error('Configuration Python file not found');
  if (!fs.statSync(modelingPath).isFile()) throw new Error('Modeling Python file not found');
  for (const [key, file] of [['AutoConfig', configurationPath], ['AutoModelForCausalLM', modelingPath]]) {
    const moduleName = String(configuration.auto_map?.[key] || '').split('.')[0];
    if (moduleName !== path.basename(file, '.py')) throw new Error(`config.json auto_map.${key} must point to ${path.basename(file)}`);
  }
  const summary = JSON.stringify(configuration, null, 2).split('\n').map(line => `# ${line}`).join('\n');
  const header = `# Generated by BananaAll for this custom architecture.\n# Config: ${configPath}\n# Configuration Python: ${configurationPath}\n# Modeling: ${modelingPath}\n# Review the custom loading path in make_model() before running.\n# Configuration supplied for this run:\n${summary}\n\n`;
  return header + source;
});

function runCollect(args, python, timeoutMs = 90000) {
  return new Promise((resolve, reject) => {
    const child = spawn(pythonBin(python), args, { cwd: backend, env: { ...process.env, PYTHONUNBUFFERED: '1' } });
    let stdout = '', stderr = '';
    const timer = setTimeout(() => { child.kill('SIGTERM'); reject(new Error('Python worker timed out.')); }, timeoutMs);
    child.stdout.on('data', d => { stdout += d; });
    child.stderr.on('data', d => { stderr += d; });
    child.on('error', err => { clearTimeout(timer); reject(err); });
    child.on('close', code => {
      clearTimeout(timer);
      if (code !== 0) return reject(new Error(stderr.trim() || stdout.trim() || `Python exited with ${code}`));
      try { resolve(JSON.parse(stdout.trim())); } catch { reject(new Error(stderr.trim() || 'Could not parse dataset preview')); }
    });
  });
}
ipcMain.handle('inspect-dataset', async (_e, source, python) => {
  return runCollect([path.join(backend, 'inspect_dataset.py'), JSON.stringify(source)], python);
});
ipcMain.handle('auth-status', async (_e, python) => runCollect([path.join(backend, 'auth_status.py')], python, 20000));
ipcMain.handle('device-status', async (_e, python) => runCollect([path.join(backend, 'device_status.py')], python, 30000));
ipcMain.handle('export-notebook', async (_e, config, code) => {
  const repositories = validateNotebookConfig(config);
  const auth = await runCollect([path.join(backend, 'export_auth.py'), JSON.stringify(repositories)], config.python, 90000);
  const { script, zipName, tokenEmbedded } = buildNotebook(config, backend, code, auth.token);
  const result = await dialog.showSaveDialog(window, {
    title: 'Save notebook training script',
    defaultPath: path.join(app.getPath('documents'), `${safeName(config.runName)}-notebook.py`),
    filters: [{ name: 'Python script', extensions: ['py'] }]
  });
  if (result.canceled || !result.filePath) return null;
  fs.writeFileSync(result.filePath, script, { encoding: 'utf8', mode: 0o600 });
  if (tokenEmbedded && process.platform !== 'win32') fs.chmodSync(result.filePath, 0o600);
  return { path: result.filePath, zipName, tokenEmbedded, tokenNeeded: auth.tokenNeeded };
});

ipcMain.handle('start-job', async (_e, kind, config, code) => {
  if (!['train', 'evaluate', 'infer'].includes(kind)) throw new Error('Unknown job type');
  const id = crypto.randomUUID();
  const baseDirectory = config.outputDir || path.join(app.getPath('documents'), 'BananaAll', 'runs');
  const runName = safeName(config.runName || `run-${id.slice(0, 8)}`);
  let output = path.resolve(baseDirectory, kind === 'train' ? runName : `job-${id.slice(0, 8)}`);
  if (kind === 'train' && !config.resumeCheckpoint) {
    let suffix = 2;
    while (fs.existsSync(output) && (!fs.statSync(output).isDirectory() || fs.readdirSync(output).length > 0)) {
      output = path.resolve(baseDirectory, `${runName}-${suffix++}`);
    }
  }
  fs.mkdirSync(output, { recursive: true });
  const configFile = path.join(output, 'bananaall-config.json');
  fs.writeFileSync(configFile, JSON.stringify({ ...config, outputPath: output }, null, 2));
  let script = path.join(backend, `${kind}.py`);
  if (kind === 'train' && typeof code === 'string' && code.trim()) {
    script = path.join(output, 'training_code.py');
    fs.writeFileSync(script, code);
  }
  const child = spawn(pythonBin(config.python), [script, configFile], { cwd: backend, env: { ...process.env, PYTHONUNBUFFERED: '1', PYTHONPATH: `${backend}${path.delimiter}${process.env.PYTHONPATH || ''}` } });
  jobs.set(id, child);
  let buffer = '';
  child.stdout.on('data', chunk => {
    buffer += chunk.toString();
    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop();
    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        const event = JSON.parse(line);
        if (event.type === 'complete') completedJobs.add(id);
        send({ id, ...event });
      }
      catch { send({ id, type: 'log', message: line }); }
    }
  });
  child.stderr.on('data', chunk => send({ id, type: 'log', message: chunk.toString() }));
  child.on('error', err => { jobs.delete(id); send({ id, type: 'error', message: err.message }); });
  child.on('close', (code, signal) => {
    jobs.delete(id);
    if (buffer.trim()) send({ id, type: 'log', message: buffer });
    if (!stoppingJobs.has(id) && (signal || code !== 0 || !completedJobs.has(id))) {
      const reason = signal ? `signal ${signal}` : code !== 0 ? `code ${code}` : 'code 0 without a complete event';
      send({ id, type: 'error', message: `${kind} worker exited with ${reason}. Output: ${output}.` });
    }
    send({ id, type: 'exit', code, signal, outputPath: output });
    stoppingJobs.delete(id);
    completedJobs.delete(id);
  });
  return { id, outputPath: output };
});
ipcMain.handle('stop-job', async (_e, id) => {
  const child = jobs.get(id);
  if (!child) return false;
  stoppingJobs.add(id);
  child.kill('SIGTERM');
  return true;
});
